---
- name: Ensure admin host is reachable
  hosts: admin
  roles:
  - role: ping

- name: Setup libvirt host
  hosts: admin
  roles:
  - role: libvirt-host

- name: Create Debian Server
  hosts: deb12
  gather_facts: false
  roles:
  - role: libvirt-domain

- name: Setup Debian Server
  hosts: deb12
  gather_facts: true
  roles:
  - role: debian-server

- name: Setup Ollama Server
  hosts: deb12
  gather_facts: true
  roles:
  - role: ollama-server
